/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: d+BIoz5YIlUXNhBxUgBrc/V5rG5Pj/sHY3pUI63KfLhEDGclLbp1n/Wp+H5YceT65xIcD44uak2EKPP8Y9ByyA==
 */

/* eslint-disable */
// tslint:disable

import Accounts from './Accounts'

interface Events {
  description: string
  end: (string | Date)
  hostId: Accounts['id']
  id: number & {readonly __brand?: 'Events_id'}
  imagePath: (string) | null
  location: string
  name: string
  start: (string | Date)
}
export default Events;

interface Events_InsertParameters {
  description?: string
  end: (string | Date)
  hostId: Accounts['id']
  id: number & {readonly __brand?: 'Events_id'}
  imagePath?: (string) | null
  location: string
  name: string
  start: (string | Date)
}
export type {Events_InsertParameters}
