/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: OZu/QH1O/UqwE9fmtptPZGFtNpy7TQnJQLIgWOO/epOHf5lW1V6IsspYQMxO3/ltGqOQcrAGDlGF/juz6jzmaw==
 */

/* eslint-disable */
// tslint:disable

import Accounts, {Accounts_InsertParameters} from './Accounts'
import Events, {Events_InsertParameters} from './Events'

interface DatabaseSchema {
  Accounts: {record: Accounts, insert: Accounts_InsertParameters};
  Events: {record: Events, insert: Events_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
